-- Seed compétences (idempotent sur source_roadmap)
delete from public.competences_preuves
where competence_id in (select id from public.competences where source_roadmap is not null);
delete from public.competences where source_roadmap is not null;

insert into public.competences (id, arc_id, titre, description, prerequis, niveau_requis, source_roadmap, cree_le)
values
(gen_random_uuid(), 'dev', 'fCC — Responsive Web Design', 'Certification active semaine S1 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S1', now()),
(gen_random_uuid(), 'dev', 'fCC — Responsive Web Design (fin)', 'Certification active semaine S2 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S2-C1', now()),
(gen_random_uuid(), 'dev', 'Anthropic Claude 101', 'Certification active semaine S2 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S2-C2', now()),
(gen_random_uuid(), 'dev', 'fCC — JS Algorithms & Data Structures', 'Certification active semaine S3 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S3-C1', now()),
(gen_random_uuid(), 'dev', 'Building with Claude API', 'Certification active semaine S3 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S3-C2', now()),
(gen_random_uuid(), 'dev', 'CS50P — psets cœur', 'Certification active semaine S4 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S4-C1', now()),
(gen_random_uuid(), 'dev', 'DL.AI Prompt Engineering', 'Certification active semaine S4 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S4-C2', now()),
(gen_random_uuid(), 'dev', 'LangChain', 'Certification active semaine S4 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S4-C3', now()),
(gen_random_uuid(), 'dev', 'AI Fluency', 'Certification active semaine S4 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'initiation', 'LearnByDoing-S4-C4', now()),
(gen_random_uuid(), 'dev', 'fCC — Back End Development and APIs (Node+Express)', 'Certification active semaine S5 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S5-C1', now()),
(gen_random_uuid(), 'dev', 'n8n Academy Beginner', 'Certification active semaine S5 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S5-C2', now()),
(gen_random_uuid(), 'dev', 'fCC — Relational Database (PostgreSQL+Bash)', 'Certification active semaine S6 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S6-C1', now()),
(gen_random_uuid(), 'dev', 'n8n Academy Advanced', 'Certification active semaine S6 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S6-C2', now()),
(gen_random_uuid(), 'dev', 'SQL Murder Mystery', 'Certification active semaine S6 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S6-C3', now()),
(gen_random_uuid(), 'dev', 'fCC — Front End Libraries (React+Redux)', 'Certification active semaine S7 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S7', now()),
(gen_random_uuid(), 'dev', 'Docker — Play with Docker + Get Started', 'Certification active semaine S8 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S8-C1', now()),
(gen_random_uuid(), 'dev', 'Make Academy', 'Certification active semaine S8 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S8-C2', now()),
(gen_random_uuid(), 'dev', 'Zapier', 'Certification active semaine S8 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S8-C3', now()),
(gen_random_uuid(), 'dev', 'Microsoft Learn — TypeScript', 'Certification active semaine S9 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'pratique', 'LearnByDoing-S9', now()),
(gen_random_uuid(), 'dev', 'DL.AI Agentic RAG', 'Certification active semaine S10 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S10-C1', now()),
(gen_random_uuid(), 'dev', 'LlamaIndex', 'Certification active semaine S10 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S10-C2', now()),
(gen_random_uuid(), 'dev', 'MCP Advanced', 'Certification active semaine S10 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S10-C3', now()),
(gen_random_uuid(), 'dev', 'DL.AI LangGraph', 'Certification active semaine S11 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S11-C1', now()),
(gen_random_uuid(), 'dev', 'Anthropic Agent Skills', 'Certification active semaine S11 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S11-C2', now()),
(gen_random_uuid(), 'dev', 'Anthropic MCP Intro', 'Certification active semaine S12 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S12-C1', now()),
(gen_random_uuid(), 'dev', 'DeepLearning.AI CrewAI', 'Certification active semaine S12 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S12-C2', now()),
(gen_random_uuid(), 'dev', 'AWS Cloud Practitioner', 'Certification active semaine S14 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S14-C1', now()),
(gen_random_uuid(), 'dev', 'Anthropic Bedrock', 'Certification active semaine S14 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S14-C2', now()),
(gen_random_uuid(), 'dev', 'Google GenAI', 'Certification active semaine S14 (BigFis Learn By Doing v7). Source: docs/roadmaps/BigFis_LearnByDoing_FINAL_v7.pdf', '{}', 'maitrise', 'LearnByDoing-S14-C3', now()),
(gen_random_uuid(), 'beatmaker', 'S1 — Anatomie d''un hit — déconstruire pour comprendre', 'Phase: How to Arrange a Beat Like a Pro — Busy Works Beats
Objectifs: Déconstruire 5 sons référence (Trap, R&B, Dancehall) dans FL Studio; Identifier chaque section : intro, verse, pre-hook, hook, bridge, outro; Repérer les techniques de tension/release utilisées; Cartographier l''énergie d''un son sur une timeline (haut/bas/pivot)
Skills: Arrangement View, Song Structure, Référencement, Analyse sonore
Projet: Importer 3 sons référence dans FL Studio et annoter chaque section dans l''Arrangement View. Exporter un screenshot commenté.
Ressources: How to Arrange a Beat Like a Pro — Busy Works Beats <https://www.youtube.com/watch?v=9mR2wFaE9Oo>; Song Structure For Beatmakers — Curtiss King TV <https://www.youtube.com/watch?v=GE4oijS5zZ8>; FL Studio Arrangement View — Guide complet <https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/arranger.htm>; Référence : "Knife Talk" de Drake — analyse structure <https://www.youtube.com/watch?v=HxbFAP-YMBo>', '{}', 'initiation', 'Beatmaker-P1-SS1', now()),
(gen_random_uuid(), 'beatmaker', 'S2 — Les 7 techniques d''enrichissement de mélodie', 'Phase: Référence : "Knife Talk" de Drake — analyse structure
Objectifs: Technique 1 : Call & Response — mélodie qui "répond" à elle-même; Technique 2 : Variation rythmique — même notes, timing différent; Technique 3 : Octave jump — monter ou descendre d''une octave pour intensité; Technique 4 : Contre-mélodie — 2e ligne mélodique qui complète la 1ère; Technique 5 : Fill de transition — 2-4 notes avant le changement de section; Technique 6 : Silence stratégique — le vide comme élément musical; Technique 7 : Modulation de vélocité pour l''expression
Skills: Call & Response, Counter Melody, Velocity, Fills
Projet: Prendre une de tes mélodies existantes et appliquer 4 techniques différentes. Exporter 4 versions et comparer.
Ressources: How To Make Your Melodies More Interesting — ADSR Sounds <https://www.youtube.com/watch?v=XcSrqtAA3_Y>; Counter Melody Tutorial FL Studio — Underbelly <https://www.youtube.com/watch?v=9E1Y3nEMqY4>; Melodic Development — Coursera Berklee <https://www.coursera.org/learn/music-production>; Écoute : "Essence" de Wizkid — contre-mélodie parfaite <https://www.youtube.com/watch?v=YNJUMbFZuqA>', '{}', 'maitrise', 'Beatmaker-P4-SS2', now()),
(gen_random_uuid(), 'beatmaker', 'S3 — Progression harmonique & changements de section', 'Phase: Écoute : "Essence" de Wizkid — contre-mélodie parfaite
Objectifs: Maîtriser les progressions classiques : i–VI–III–VII, ii–V–I, 1–4–5; Changer la progression entre verse et hook pour créer une surprise émotionnelle; Utiliser les modes (dorien, phrygien) pour la couleur exotique Afro/Dancehall; Créer un pré-hook qui monte en tension avant l''explosion du drop
Skills: Progressions, Modes, Harmonie, Pre-hook
Projet: Créer un beat complet (2 min min.) avec au moins 2 progressions différentes entre verse et hook.
Ressources: Chord Progressions for Trap & R&B — Manny Music <https://www.youtube.com/watch?v=6IfGBpuNIlA>; Hook Theory — théorie musicale interactive <https://www.hooktheory.com/theorytab>; Phrygian Mode for Caribbean/Afro beats — explanation <https://www.youtube.com/watch?v=dDqVZe9EAHU>; Claude : "Génère 5 progressions d''accords en mode dorien pour un beat afro" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P8-SS3', now()),
(gen_random_uuid(), 'beatmaker', 'S4 — Dynamique & énergie sur toute la durée', 'Phase: Phrygian Mode for Caribbean/Afro beats — explanation
Objectifs: Appliquer le principe "high point" : chaque son doit avoir un climax identifiable; Techniques de build-up : filter sweep, riser, mute progressif des éléments; Le breakdown : enlever des éléments pour créer de l''espace et de l''anticipation; Automatisation de paramètres pour une prod vivante (volume, reverb send, pan)
Skills: Automation, Build-up, Breakdown, Dynamique
Projet: Terminer un beat complet de 2min30 avec intro / build / drop / breakdown / final drop. Automatiser au moins 4 paramètres.
Ressources: How to Build Energy in Your Beats — Underbelly <https://www.youtube.com/watch?v=eZ1U3N8pJLQ>; FL Studio Automation Tutorial — Busy Works Beats <https://www.youtube.com/watch?v=JQpfPpXUkuQ>; Build-up & Breakdown techniques — In The Mix <https://www.youtube.com/watch?v=Mj0KH3ZBVZQ>; Référence : "What''s Luv" — architecture sonore parfaite <https://www.youtube.com/watch?v=kBPiWa0yWzQ>', '{}', 'maitrise', 'Beatmaker-P11-SS4', now()),
(gen_random_uuid(), 'beatmaker', 'S5 — Pattern & pocket — faire groover le kick et la snare', 'Phase: Build-up & Breakdown techniques — In The Mix
Objectifs: Comprendre le concept de "pocket" — jouer légèrement avant ou après le temps; Humaniser les velocities dans le Step Sequencer de FL Studio; Créer des variations de snare (ghost notes, rolls, snare flam); Comparer et analyser des drum patterns de Murda Beatz, Southside, Rvssian
Skills: Step Sequencer, Velocity, Ghost Notes, Pocket
Projet: Créer 3 drum patterns différents (Trap, R&B laid back, Dancehall) avec humanisation des velocities. Tous en 8 bars minimum.
Ressources: How to Make Your Drums Groove — Zen Music Group <https://www.youtube.com/watch?v=fZOt0mXN5bY>; Ghost Notes & Humanization FL Studio — Busy Works Beats <https://www.youtube.com/watch?v=bHfQE8LQbBg>; Trap Drum Programming — Produce Like The Pros <https://www.youtube.com/watch?v=1gBUhHUf30k>; Déconstruction : drums de "SICKO MODE" — Travis Scott <https://www.youtube.com/watch?v=y_mcHWxp4iY>', '{}', 'maitrise', 'Beatmaker-P15-SS5', now()),
(gen_random_uuid(), 'beatmaker', 'S6 — Drum Design — créer tes propres 808s et snares', 'Phase: Déconstruction : drums de "SICKO MODE" — Travis Scott
Objectifs: Comprendre la synthèse d''un 808 : pitch slide, decay, saturation dans FL Studio; Designer une snare signature à partir de zéro avec des samples layerisés; Tuner tes 808s en fonction de la tonalité de la mélodie; Créer un hi-hat pattern afro/dancehall avec le swing et le "chuga chuga"
Skills: 808 Design, Snare Layering, Tuning, Afro Hi-Hat
Projet: Designer un 808 custom, une snare custom, et un pattern hi-hat afro. Créer un beat qui showcase les 3.
Ressources: 808 Design From Scratch FL Studio — BrainDead Beats <https://www.youtube.com/watch?v=dR7O5Ah9mGc>; Tune Your 808 to Your Melody — In The Mix <https://www.youtube.com/watch?v=0UmFdQZK2k8>; Dancehall Hi-Hat Patterns FL Studio — Yaadcore <https://www.youtube.com/results?search_query=dancehall+drum+pattern+fl+studio>; Plugin : Gross Beat pour les effets rythmiques <https://www.image-line.com/plugins/Effects/Gross+Beat/>', '{}', 'maitrise', 'Beatmaker-P20-SS6', now()),
(gen_random_uuid(), 'beatmaker', 'S7 — Fills, transitions et drum storytelling', 'Phase: Plugin : Gross Beat pour les effets rythmiques
Objectifs: Créer des drum fills qui annoncent un changement de section sans le casser; Technique : muter le kick sur le dernier temps avant le drop pour de l''anticipation; Reverse cymbal + riser sur les transitions; Utiliser Gross Beat pour les stutter effects et les crash intentionnels
Skills: Drum Fills, Stutter FX, Gross Beat, Transitions
Projet: Créer un beat de 2 min avec au minimum 4 transitions distinctes, chacune avec une technique différente.
Ressources: Drum Transitions & Fills FL Studio — Busy Works Beats <https://www.youtube.com/watch?v=ZfQFroV8_8o>; Gross Beat Stutter Effect Tutorial — BrainDead Beats <https://www.youtube.com/watch?v=lPdgF_oCyGI>; Reverse Cymbal Technique — Underbelly <https://www.youtube.com/watch?v=t8zWiMG5R8E>; Claude : "Décris 5 types de drum fills pour transitions Trap vs R&B" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P24-SS7', now()),
(gen_random_uuid(), 'beatmaker', 'S8 — Live drums feel & groove hybride', 'Phase: Claude : "Décris 5 types de drum fills pour transitions Trap vs R&B"
Objectifs: Combiner drums samples de kit live avec des drum machines pour un son hybride; Appliquer un swing global sur un pattern dans FL Studio; Comprendre la différence de groove : Trap US vs Afrobeats vs Dancehall; Créer ton propre groove "signature" reconnaissable
Skills: Swing, Groove Hybride, Live Drums, Signature sonore
Projet: Produire un beat hybride qui mixe éléments Trap et Afro/Dancehall avec ton groove signature. 2 min minimum.
Ressources: Swing & Groove Settings FL Studio — Busy Works Beats <https://www.youtube.com/watch?v=YIl6UD_OJXE>; Afrobeats Drum Pattern From Scratch — KassBeats <https://www.youtube.com/watch?v=yz_GhJSe8uk>; Hybrid Drum Production — Splice Blog <https://splice.com/blog/hybrid-drums-production-tips/>; Écoute : Burna Boy — "On The Low" (groove afro reference) <https://www.youtube.com/watch?v=YE70-pWOECk>', '{}', 'maitrise', 'Beatmaker-P28-SS8', now()),
(gen_random_uuid(), 'beatmaker', 'S9 — Les bases du mix — espace, balance & fréquences', 'Phase: Écoute : Burna Boy — "On The Low" (groove afro reference)
Objectifs: Comprendre le spectre fréquentiel (sub, bass, mids, highs) et l''espace de chaque élément; Faire une balance de gain propre avant tout EQ ou compression; High-pass filter sur tous les éléments qui ne font pas partie des basses; Sidechaining kick → 808 pour que les deux coexistent sans conflit
Skills: Gain Staging, EQ, High-Pass Filter, Sidechain
Projet: Reprendre ton dernier beat et nettoyer entièrement le mix : gain staging + HPF sur tous les éléments + sidechain.
Ressources: Mixing For Beginners — In The Mix (complet) <https://www.youtube.com/watch?v=MEJmMeOKPKg>; Frequency Spectrum Explained — FabFilter Tutorial <https://www.youtube.com/watch?v=pLu9FeaXvUE>; FL Studio Mixer — guide officiel Image-Line <https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/mixer.htm>; Plugin : Parametric EQ 2 (natif FL) — maîtriser ses courbes <https://www.image-line.com/plugins/Effects/Parametric+EQ+2/>', '{}', 'maitrise', 'Beatmaker-P32-SS9', now()),
(gen_random_uuid(), 'beatmaker', 'S10 — Compression — contrôle & punch', 'Phase: Plugin : Parametric EQ 2 (natif FL) — maîtriser ses courbes
Objectifs: Comprendre Attack, Release, Ratio, Threshold, Knee; Compression sur les drums pour le punch : attaque lente, release rapide; Parallel compression (New York style) : compresser fort sur une copie, blender; Multiband compression pour contrôler les basses sans affecter les aigus
Skills: Compression, Parallel Comp, Attack/Release, Multiband
Projet: Appliquer compression + parallel compression sur les drums d''un beat. Comparer avant/après. Documenter les réglages.
Ressources: Compression Explained Simply — Produce Like The Pros <https://www.youtube.com/watch?v=H6BPF2OMeCo>; Parallel Compression Tutorial FL Studio — BrainDead Beats <https://www.youtube.com/watch?v=6GtHrA2_Z5c>; How To Mix 808s Properly — In The Mix <https://www.youtube.com/watch?v=0bW8JrBJN9Y>; Plugin : Fruity Peak Controller pour sidechain dynamique <https://www.image-line.com/plugins/Effects/Peak+Controller/>', '{}', 'maitrise', 'Beatmaker-P36-SS10', now()),
(gen_random_uuid(), 'beatmaker', 'S11 — Saturation, harmoniques & largeur stéréo', 'Phase: Plugin : Fruity Peak Controller pour sidechain dynamique
Objectifs: Saturation pour ajouter de la chaleur sur la mélodie et les samples; Stéréo widening sans phase issues : Haas effect, mid-side EQ; Reverb & delay : espace et profondeur sans noyer le mix; Référencer ton mix avec des sons compétitifs sur Soundcloud / Apple Music
Skills: Saturation, Stereo Width, Reverb, Référencement
Projet: Ajouter saturation + stéréo widening sur une mélodie et comparer avec un son de référence sur les mêmes enceintes.
Ressources: Saturation Tutorial — Everything You Need To Know <https://www.youtube.com/watch?v=YbgMlO-3G8A>; Stereo Width Without Phase Issues — In The Mix <https://www.youtube.com/watch?v=H3OuQkAsHkg>; Reverb & Delay for Beatmakers — Underbelly <https://www.youtube.com/watch?v=E5F1y5lzOzY>; Plugin : Fruity Stereo Shaper (natif) pour la largeur <https://www.image-line.com/plugins/Effects/Stereo+Shaper/>', '{}', 'maitrise', 'Beatmaker-P40-SS11', now()),
(gen_random_uuid(), 'beatmaker', 'S12 — Loudness & mastering à l''export', 'Phase: Plugin : Fruity Stereo Shaper (natif) pour la largeur
Objectifs: Cibler -14 LUFS pour streaming, -9 LUFS pour placements agressifs; Limiter sans distorsion : True Peak limiter en fin de chaîne; Exporter en WAV 24bit / 44.1kHz proprement depuis FL Studio; A/B test de ton master avec 3 sons compétitifs du même genre
Skills: LUFS, True Peak, Mastering, Export FL Studio
Projet: Mastering complet d''un de tes beats. Comparer le LUFS avant/après avec Youlean Loudness Meter. Export final propre.
Ressources: Mastering For Streaming — Youlean Loudness Tutorial <https://www.youtube.com/watch?v=j7P8zFxbOA4>; FL Studio Export Settings For Beats — 2024 <https://www.youtube.com/watch?v=9LRGPhQeYaU>; Plugin : Maximus (natif FL) pour le mastering final <https://www.image-line.com/plugins/Effects/Maximus/>; Loudness Standards — Spotify, Apple Music, YouTube <https://www.loudnesspenalty.com/>', '{}', 'maitrise', 'Beatmaker-P44-SS12', now()),
(gen_random_uuid(), 'beatmaker', 'S13 — Sound design — créer des sons que personne d''autre a', 'Phase: Loudness Standards — Spotify, Apple Music, YouTube
Objectifs: Synthèse de base dans FL : comprendre wavetable, FM, subtractive dans Harmor/Sytrus; Créer 3 textures uniques : un pad atmosphérique, un lead gritty, un pluck perlé; Transformer un son naturel (voix, objet) en instrument via sampling créatif; Construire une banque de 20 sons custom — ta bibliothèque signature
Skills: Sytrus, Harmor, Wavetable, Sound Design
Projet: Designer 5 sons 100% originaux dans Sytrus ou Harmor. Les assembler dans un beat pour démontrer leur cohérence.
Ressources: Sound Design From Scratch FL Studio Sytrus — BrainDead <https://www.youtube.com/watch?v=w5PVWVQ0oaY>; Harmor Sound Design Tutorial — In The Mix <https://www.youtube.com/watch?v=bfJGFNkp-RU>; Creative Sampling — Turn Anything Into A Beat <https://www.youtube.com/watch?v=vPuvdDI1fCY>; Claude : "Donne-moi 10 idées de sons à synthétiser pour un beat afro-trap unique" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P48-SS13', now()),
(gen_random_uuid(), 'beatmaker', 'S14 — Sampling avancé & crate digging digital', 'Phase: Claude : "Donne-moi 10 idées de sons à synthétiser pour un beat afro-trap unique"
Objectifs: Crate digging intelligent : musiques traditionnelles malgaches, afro, jamaïcaines; Chop et pitch des samples dans le Edison Recorder de FL Studio; Timestretching créatif pour créer des textures inhabituelles; Comprendre le copyright et comment clearer ou éviter les problèmes légaux
Skills: Edison, Timestretch, Crate Digging, Copyright
Projet: Créer un beat entièrement basé sur un sample d''une musique malgache ou caribéenne transformée de façon méconnaissable.
Ressources: How To Sample Properly FL Studio — Busy Works Beats <https://www.youtube.com/watch?v=Xb-TxuU_Bak>; Creative Sampling Techniques — Sampling Like Kanye <https://www.youtube.com/watch?v=6E-rkSN79_s>; Sample Clearance 101 — Complete Guide for Producers <https://www.musicgateway.com/blog/how-to/sample-clearance>; Écoute : "Runaway" de Kanye — sampling sublimé <https://www.youtube.com/watch?v=Bm5iA4Zupek>', '{}', 'maitrise', 'Beatmaker-P52-SS14', now()),
(gen_random_uuid(), 'beatmaker', 'S15 — Définir ta niche et ton identité de marque', 'Phase: Écoute : "Runaway" de Kanye — sampling sublimé
Objectifs: Identifier les 3 mots qui définissent TON son (ex: dark / mélodique / caribbean); Créer un "moodboard" sonore : 10 sons référence qui représentent ton identité; Nommer ta niche : Trap Malgache, Caribbean Dark Trap, Afro-R&B Océan Indien...; Écrire ta biographie de producteur en 100 mots pour les placements
Skills: Branding, Moodboard, Niche, Identity
Projet: Créer un pack de 3 beats cohérents qui définissent ton identité sonore. Écrire les notes de présentation de chaque son.
Ressources: How To Find Your Sound As A Producer — Curtiss King TV <https://www.youtube.com/watch?v=L5dN4FmvxeA>; Building a Producer Brand in 2024 — Busy Works Beats <https://www.youtube.com/watch?v=XY3H3Pu0X5A>; Music Producer Branding — DIY Musician (CD Baby) <https://diymusician.cdbaby.com/music-promotion/music-producer-branding/>; Claude : "Aide-moi à définir ma niche de beatmaker avec ces influences : [tes influences]" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P56-SS15', now()),
(gen_random_uuid(), 'beatmaker', 'S16 — Construire ta banque de sons & templates', 'Phase: Claude : "Aide-moi à définir ma niche de beatmaker avec ces influences : [tes influences]"
Objectifs: Organiser ta bibliothèque de samples et presets dans FL Studio proprement; Créer un template de projet FL Studio avec ta chaîne de mix déjà paramétrée; Constituer une banque de loops, fills et transitions signature réutilisables; Versionner tes projets avec un système de naming clair
Skills: Templates, Workflow, Organisation, Productivité
Projet: Créer et documenter ton template FL Studio complet. Produire un beat entier en moins de 2h en partant de ce template.
Ressources: FL Studio Template Setup For Faster Workflow — Underbelly <https://www.youtube.com/watch?v=9Jf3OqPNKiM>; Organizing Your Sample Library — Produce Like The Pros <https://www.youtube.com/watch?v=G9_Q_paqBuA>; FL Studio Project Organization — Image-Line Guide <https://www.image-line.com/fl-studio-learning/>; Plugin : Patcher dans FL pour créer des effets chaînés custom <https://www.image-line.com/plugins/Synths/Patcher/>', '{}', 'maitrise', 'Beatmaker-P60-SS16', now()),
(gen_random_uuid(), 'beatmaker', 'S17 — Plateforme de vente — setup BeatStars & Traktrain', 'Phase: Plugin : Patcher dans FL pour créer des effets chaînés custom
Objectifs: Créer et optimiser ta page BeatStars (bio, tags, artwork, prix); Comprendre les types de licences : non-exclusive, exclusive, unlimited; Définir ta grille tarifaire adaptée au marché international; Uploader tes 10 meilleurs sons avec tags SEO optimisés pour la recherche
Skills: BeatStars, SEO Tags, Licensing, Pricing
Projet: Page BeatStars complète avec 10 sons uploadés, tags SEO, prix définis, et bio de producteur.
Ressources: BeatStars Setup Guide 2024 — Busy Works Beats <https://www.youtube.com/watch?v=XNyeEV5yDyQ>; Beat Licensing Explained — Music Lawyer Breakdown <https://www.youtube.com/watch?v=OkPkYH_7wV4>; How to Price Your Beats — Curtiss King <https://www.youtube.com/watch?v=FH5dCKb0Lio>; Claude : "Aide-moi à écrire 5 descriptions SEO pour mes beats Afro-Trap" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P64-SS17', now()),
(gen_random_uuid(), 'beatmaker', 'S18 — Content & réseaux sociaux pour beatmakers', 'Phase: Claude : "Aide-moi à écrire 5 descriptions SEO pour mes beats Afro-Trap"
Objectifs: Stratégie contenu : TikTok beats, YouTube playback, Instagram reels; Format "making-of" : filmer ton processus de prod en time-lapse; Créer une série de posts hebdomadaires : "Beat of the Week"; Engager la communauté francophone ET anglophone d''artistes
Skills: TikTok, YouTube Shorts, Content Calendar, Engagement
Projet: Publier 15 posts en 3 semaines (5 TikTok, 5 Instagram, 5 YouTube Shorts). Analyser les stats.
Ressources: TikTok Marketing For Beatmakers — Treyton Woodruff <https://www.youtube.com/watch?v=5VauvhTTuFE>; YouTube Channel For Beats — Setup & Growth Tips <https://www.youtube.com/watch?v=LzKMVMUhiN4>; Social Media for Music Producers — SubmitHub Blog <https://blog.submithub.com/producers-social-media>; Claude : "Crée un calendrier de contenu 30j pour un beatmaker avec ma niche" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P68-SS18', now()),
(gen_random_uuid(), 'beatmaker', 'S19 — Placements & networking avec les artistes', 'Phase: Claude : "Crée un calendrier de contenu 30j pour un beatmaker avec ma niche"
Objectifs: Identifier 50 artistes francophone/créole/anglophone dans ta niche à démarcher; Envoyer des beats personnalisés : "J''ai fait ce beat en pensant à toi"; Rejoindre les communautés Discord et Reddit de producers et d''artistes; Collaborer avec des artistes malgaches et de l''Océan Indien pour construire ton réseau local
Skills: Cold Outreach, Networking, Placement, Discord
Projet: Envoyer 30 beats personnalisés à 30 artistes différents. Documenter les réponses et affiner le message.
Ressources: How To Get Placements — Reach Out Strategy — Busy Works Beats <https://www.youtube.com/watch?v=kLbI5PJmS_c>; Reddit r/WeAreTheMusicMakers — communauté de producteurs <https://www.reddit.com/r/WeAreTheMusicMakers/>; Instagram DM Strategy For Getting Placements — Treyton <https://www.youtube.com/watch?v=9mGPu_bHY7c>; Claude : "Écris un message de démarchage professionnel pour envoyer un beat à un artiste" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P72-SS19', now()),
(gen_random_uuid(), 'beatmaker', 'S20 — Revenu récurrent — packs, exclusivités & retainers', 'Phase: Claude : "Écris un message de démarchage professionnel pour envoyer un beat à un artiste"
Objectifs: Créer et vendre des sample packs avec ton son signature sur Splice ou BeatStars; Proposer des contrats de producteur exclusif à 1-2 artistes qui cartonnent; Monétiser tes YouTube beats avec Content ID via DistroKid ou TuneCore; Objectif : atteindre 200$/mois de revenus passifs dans les 6 mois
Skills: Sample Packs, Content ID, Passive Income, Retainer
Projet: 🎯 Lancer ton premier sample pack (20 sons minimum) sur une plateforme. Objectif : 5 premières ventes.
Ressources: How to Sell Sample Packs on Splice — Full Guide <https://www.youtube.com/watch?v=HNKchR0xnW0>; Content ID for Beats — DistroKid vs TuneCore <https://www.youtube.com/watch?v=yg1v2nEdFss>; Passive Income as a Music Producer 2024 — Curtiss King <https://www.youtube.com/watch?v=VcnrT9vRlLk>; Claude : "Aide-moi à créer une offre de retainer pour un artiste : contenu, prix, conditions" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P76-SS20', now()),
(gen_random_uuid(), 'beatmaker', 'S21-24 — Consolidation — analyse, scale & legacy', 'Phase: Claude : "Aide-moi à créer une offre de retainer pour un artiste : contenu, prix, conditions"
Objectifs: Analyser tous les sons vendus / placés : qu''est-ce qui a marché et pourquoi ?; Doubler la production sur les formats et styles les plus performants; Créer une newsletter ou communauté privée pour tes clients et fans; Planifier l''année 2 : collaboration internationale, prod trip, label propre ?; Documenter ta progression : tu es passé de "les gens se lassent" à référence
Skills: Analytics, Community, Scale, Legacy
Projet: 🏆 Bilan complet des 6 mois : stats de ventes, placements obtenus, sons produits, audience. Roadmap Year 2 rédigée.
Ressources: Music Producer Year in Review — What to Analyze <https://www.youtube.com/watch?v=d6JPhFJUPm8>; Building a Music Producer Community — ConvertKit Guide <https://convertkit.com/resources/blog/musician-email-list>; Going From Bedroom Producer to Industry — Manny Music <https://www.youtube.com/watch?v=MsOuI5wLpgg>; Claude : "Analyse mon parcours de 6 mois et aide-moi à planifier l''année 2" <https://claude.ai>', '{}', 'maitrise', 'Beatmaker-P80-SS21-24', now());
